// Package tlscert generates and persists a local self-signed root CA plus a
// server certificate signed by it, for Miranda's own optional HTTPS
// listener (config.ServerConfig.TLS) — so a deployment that wants direct
// HTTPS to Miranda doesn't need a separate ACME setup or reverse proxy just
// to get a cert on disk.
//
// Two certificates, not one: a single certificate can't be both a trust
// anchor (CA:TRUE, importable into a browser's "Authorities" store) and a
// TLS server certificate at the same time — Firefox's verifier
// (mozilla::pkix) explicitly rejects a CA:TRUE cert presented as an end
// entity (MOZILLA_PKIX_ERROR_CA_CERT_USED_AS_END_ENTITY), even though
// Chrome/Safari and the underlying TLS handshake itself don't care. So this
// mirrors what mkcert and similar tools do: a long-lived root CA that never
// leaves this pair of files (only its public half, ca.pem, needs
// installing into a device's trust store), and a leaf server certificate —
// the one actually presented over the wire — signed by that CA and
// regenerated independently.
package tlscert

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"log/slog"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"time"
)

// validity is how long a generated certificate (root CA or leaf alike)
// lasts. Long-lived on purpose: there's no ACME renewal loop behind this,
// so a shorter expiry would just mean a human has to notice and regenerate
// it — not worth the marginal security gain for what's typically LAN/home
// use.
const validity = 10 * 365 * 24 * time.Hour

// caCertFilename and caKeyFilename name the root CA's own files, kept
// alongside the leaf cert/key in the same directory. Only ca.pem needs
// installing into a browser/OS trust store — ca-key.pem never leaves the
// server, same as the leaf's own key.
const (
	caCertFilename = "ca.pem"
	caKeyFilename  = "ca-key.pem"
)

// EnsureSelfSigned makes sure certPath and keyPath both exist, generating a
// fresh ECDSA P-256 leaf certificate/key pair valid for hosts (plus
// "localhost"/"127.0.0.1", always included) if neither file is present —
// signed by a root CA kept alongside it (ca.pem/ca-key.pem in the same
// directory as certPath), generating that CA too on first use. An existing
// certPath/keyPath pair — whether generated by a previous call to this
// function, or supplied by the operator (e.g. a certificate from a real
// CA) — is left untouched: this only ever fills in what's absent, never
// validates or rotates what's already on disk.
func EnsureSelfSigned(certPath, keyPath string, hosts []string, logger *slog.Logger) error {
	_, certErr := os.Stat(certPath)
	_, keyErr := os.Stat(keyPath)
	if certErr == nil && keyErr == nil {
		return nil
	}
	if certErr == nil || keyErr == nil {
		return fmt.Errorf("tlscert: %s and %s must either both exist or both be absent (only one was found)", certPath, keyPath)
	}

	dir := filepath.Dir(certPath)
	caCertPath := filepath.Join(dir, caCertFilename)
	caKeyPath := filepath.Join(dir, caKeyFilename)

	caCert, caKey, err := ensureRootCA(caCertPath, caKeyPath)
	if err != nil {
		return fmt.Errorf("tlscert: prepare root CA: %w", err)
	}

	leafKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("tlscert: generate key: %w", err)
	}

	serial, err := newSerial()
	if err != nil {
		return fmt.Errorf("tlscert: generate serial number: %w", err)
	}

	template := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: "Miranda"},
		// Backdated by an hour to tolerate clock skew between this host and
		// whatever verifies the cert first.
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(validity),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		// IsCA left false: this is the end-entity cert Miranda actually
		// presents on the wire — see the package doc for why it must stay
		// separate from the CA.
	}
	addSANHosts(template, hosts)

	der, err := x509.CreateCertificate(rand.Reader, template, caCert, &leafKey.PublicKey, caKey)
	if err != nil {
		return fmt.Errorf("tlscert: create certificate: %w", err)
	}

	if err := writeCertPEM(certPath, der); err != nil {
		return err
	}
	if err := writeKeyPEM(keyPath, leafKey); err != nil {
		return err
	}

	logger.Info("tlscert: generated server certificate signed by local root CA",
		"cert", certPath, "key", keyPath, "ca_cert", caCertPath,
		"dns_names", template.DNSNames, "ip_addresses", template.IPAddresses,
		"expires", template.NotAfter.Format(time.RFC3339),
		"note", "install ca_cert (not cert) into browser/OS trust stores")
	return nil
}

// ensureRootCA loads the root CA at caCertPath/caKeyPath if both already
// exist, generating a fresh self-signed one otherwise. Returned as a parsed
// *x509.Certificate (with Raw populated) since that's what
// x509.CreateCertificate needs as the parent when signing a leaf cert.
func ensureRootCA(caCertPath, caKeyPath string) (*x509.Certificate, *ecdsa.PrivateKey, error) {
	_, certErr := os.Stat(caCertPath)
	_, keyErr := os.Stat(caKeyPath)
	if certErr == nil && keyErr == nil {
		return loadCA(caCertPath, caKeyPath)
	}
	if certErr == nil || keyErr == nil {
		return nil, nil, fmt.Errorf("%s and %s must either both exist or both be absent (only one was found)", caCertPath, caKeyPath)
	}

	caKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("generate root CA key: %w", err)
	}

	serial, err := newSerial()
	if err != nil {
		return nil, nil, fmt.Errorf("generate root CA serial number: %w", err)
	}

	template := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: "Miranda local root CA"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(validity),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
		// Signs leaf certs only, never further intermediate CAs.
		MaxPathLenZero: true,
	}

	der, err := x509.CreateCertificate(rand.Reader, template, template, &caKey.PublicKey, caKey)
	if err != nil {
		return nil, nil, fmt.Errorf("create root CA certificate: %w", err)
	}
	caCert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, nil, fmt.Errorf("parse freshly created root CA certificate: %w", err)
	}

	if err := writeCertPEM(caCertPath, der); err != nil {
		return nil, nil, err
	}
	if err := writeKeyPEM(caKeyPath, caKey); err != nil {
		return nil, nil, err
	}

	return caCert, caKey, nil
}

func loadCA(caCertPath, caKeyPath string) (*x509.Certificate, *ecdsa.PrivateKey, error) {
	certPEM, err := os.ReadFile(caCertPath)
	if err != nil {
		return nil, nil, fmt.Errorf("read %s: %w", caCertPath, err)
	}
	certBlock, _ := pem.Decode(certPEM)
	if certBlock == nil {
		return nil, nil, fmt.Errorf("%s: no PEM block found", caCertPath)
	}
	caCert, err := x509.ParseCertificate(certBlock.Bytes)
	if err != nil {
		return nil, nil, fmt.Errorf("parse %s: %w", caCertPath, err)
	}

	keyPEM, err := os.ReadFile(caKeyPath)
	if err != nil {
		return nil, nil, fmt.Errorf("read %s: %w", caKeyPath, err)
	}
	keyBlock, _ := pem.Decode(keyPEM)
	if keyBlock == nil {
		return nil, nil, fmt.Errorf("%s: no PEM block found", caKeyPath)
	}
	caKey, err := x509.ParseECPrivateKey(keyBlock.Bytes)
	if err != nil {
		return nil, nil, fmt.Errorf("parse %s: %w", caKeyPath, err)
	}

	return caCert, caKey, nil
}

func newSerial() (*big.Int, error) {
	return rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
}

// addSANHosts fills in template's DNSNames/IPAddresses from hosts, always
// including "localhost"/"127.0.0.1" even if the caller omitted them.
func addSANHosts(template *x509.Certificate, hosts []string) {
	seen := make(map[string]bool)
	addHost := func(h string) {
		if h == "" || seen[h] {
			return
		}
		seen[h] = true
		if ip := net.ParseIP(h); ip != nil {
			template.IPAddresses = append(template.IPAddresses, ip)
		} else {
			template.DNSNames = append(template.DNSNames, h)
		}
	}
	addHost("localhost")
	addHost("127.0.0.1")
	for _, h := range hosts {
		addHost(h)
	}
}

func writeCertPEM(path string, der []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create dir for %s: %w", path, err)
	}
	var buf bytes.Buffer
	if err := pem.Encode(&buf, &pem.Block{Type: "CERTIFICATE", Bytes: der}); err != nil {
		return fmt.Errorf("encode %s: %w", path, err)
	}
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func writeKeyPEM(path string, key *ecdsa.PrivateKey) error {
	der, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return fmt.Errorf("marshal %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create dir for %s: %w", path, err)
	}
	var buf bytes.Buffer
	if err := pem.Encode(&buf, &pem.Block{Type: "EC PRIVATE KEY", Bytes: der}); err != nil {
		return fmt.Errorf("encode %s: %w", path, err)
	}
	// 0600: unlike the certificate, this is a private key — readable only by
	// whichever user runs Miranda.
	if err := os.WriteFile(path, buf.Bytes(), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
