// Package tlscert generates and persists a self-signed TLS certificate/key
// pair for Miranda's own optional HTTPS listener (config.ServerConfig.TLS),
// so a deployment that wants direct HTTPS to Miranda doesn't need a
// separate CA, ACME setup, or reverse proxy just to get a cert on disk.
package tlscert

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"log/slog"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"time"
)

// validity is how long a generated self-signed certificate lasts. Long-lived
// on purpose: there's no ACME renewal loop behind this, so a shorter expiry
// would just mean a human has to notice and regenerate it — not worth the
// marginal security gain for what's typically LAN/home use.
const validity = 10 * 365 * 24 * time.Hour

// EnsureSelfSigned makes sure certPath and keyPath both exist, generating a
// fresh self-signed ECDSA P-256 certificate/key pair valid for hosts (plus
// "localhost"/"127.0.0.1", always included) if neither file is present. An
// existing pair — whether generated by a previous call to this function, or
// supplied by the operator (e.g. a certificate from a real CA) — is left
// untouched: this only ever fills in what's absent, never validates or
// rotates what's already on disk.
func EnsureSelfSigned(certPath, keyPath string, hosts []string, logger *slog.Logger) error {
	_, certErr := os.Stat(certPath)
	_, keyErr := os.Stat(keyPath)
	if certErr == nil && keyErr == nil {
		return nil
	}
	if certErr == nil || keyErr == nil {
		return fmt.Errorf("tlscert: %s and %s must either both exist or both be absent (only one was found)", certPath, keyPath)
	}

	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("tlscert: generate key: %w", err)
	}

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return fmt.Errorf("tlscert: generate serial number: %w", err)
	}

	template := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: "Miranda (self-signed)"},
		// Backdated by an hour to tolerate clock skew between this host and
		// whatever verifies the cert first.
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(validity),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
	}

	seen := make(map[string]bool)
	addHost := func(h string) {
		if h == "" || seen[h] {
			return
		}
		seen[h] = true
		if ip := net.ParseIP(h); ip != nil {
			template.IPAddresses = append(template.IPAddresses, ip)
		} else {
			template.DNSNames = append(template.DNSNames, h)
		}
	}
	addHost("localhost")
	addHost("127.0.0.1")
	for _, h := range hosts {
		addHost(h)
	}

	der, err := x509.CreateCertificate(rand.Reader, template, template, &priv.PublicKey, priv)
	if err != nil {
		return fmt.Errorf("tlscert: create certificate: %w", err)
	}

	keyDER, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		return fmt.Errorf("tlscert: marshal key: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(certPath), 0o755); err != nil {
		return fmt.Errorf("tlscert: create cert dir: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(keyPath), 0o755); err != nil {
		return fmt.Errorf("tlscert: create key dir: %w", err)
	}

	var certPEM bytes.Buffer
	if err := pem.Encode(&certPEM, &pem.Block{Type: "CERTIFICATE", Bytes: der}); err != nil {
		return fmt.Errorf("tlscert: encode certificate: %w", err)
	}
	if err := os.WriteFile(certPath, certPEM.Bytes(), 0o644); err != nil {
		return fmt.Errorf("tlscert: write %s: %w", certPath, err)
	}

	var keyPEM bytes.Buffer
	if err := pem.Encode(&keyPEM, &pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER}); err != nil {
		return fmt.Errorf("tlscert: encode key: %w", err)
	}
	// 0600: unlike the certificate, this is the private key — readable only
	// by whichever user runs Miranda.
	if err := os.WriteFile(keyPath, keyPEM.Bytes(), 0o600); err != nil {
		return fmt.Errorf("tlscert: write %s: %w", keyPath, err)
	}

	logger.Info("tlscert: generated self-signed certificate",
		"cert", certPath, "key", keyPath,
		"dns_names", template.DNSNames, "ip_addresses", template.IPAddresses,
		"expires", template.NotAfter.Format(time.RFC3339))
	return nil
}
